import { SplitDraft, SplitIncomingRequest, SplitItTransaction, SplitItUser, SplitRequest } from './types';

export const splitItCurrentUser: SplitItUser = {
  id: 'me',
  name: 'Rasmey Sophorn',
  initials: 'RS',
  accountId: 'AC-001-9921',
  phone: '+855 12 120 991',
  bank: 'Sathapana',
  recentTransferCount: 0,
  lastTransferAt: '2026-04-22T00:00:00.000Z',
};

export const splitItUsers: SplitItUser[] = [
  {
    id: 'u-1',
    name: 'Sophea Chan',
    initials: 'SC',
    accountId: 'AC-884-1001',
    phone: '+855 12 500 881',
    bank: 'Sathapana',
    recentTransferCount: 8,
    lastTransferAt: '2026-04-20T18:22:00.000Z',
  },
  {
    id: 'u-2',
    name: 'Dara Kim',
    initials: 'DK',
    accountId: 'AC-884-1002',
    phone: '+855 10 445 210',
    bank: 'Sathapana',
    recentTransferCount: 5,
    lastTransferAt: '2026-04-19T10:14:00.000Z',
  },
  {
    id: 'u-3',
    name: 'Sothea Ung',
    initials: 'SU',
    accountId: 'AC-884-1003',
    phone: '+855 16 221 742',
    bank: 'Sathapana',
    recentTransferCount: 3,
    lastTransferAt: '2026-04-18T07:04:00.000Z',
  },
  {
    id: 'u-4',
    name: 'Nika Touch',
    initials: 'NT',
    accountId: 'AC-884-1004',
    phone: '+855 77 449 902',
    bank: 'Sathapana',
    recentTransferCount: 2,
    lastTransferAt: '2026-04-14T13:33:00.000Z',
  },
  {
    id: 'u-5',
    name: 'Mony Vichea',
    initials: 'MV',
    accountId: 'AC-884-1005',
    phone: '+855 98 333 144',
    bank: 'Sathapana',
    recentTransferCount: 1,
    lastTransferAt: '2026-04-09T09:20:00.000Z',
  },
  {
    id: 'u-6',
    name: 'Piseth Lim',
    initials: 'PL',
    accountId: 'AC-884-1006',
    phone: '+855 93 101 220',
    bank: 'Sathapana',
    recentTransferCount: 7,
    lastTransferAt: '2026-04-20T11:05:00.000Z',
  },
  {
    id: 'u-7',
    name: 'Kanha Srun',
    initials: 'KS',
    accountId: 'AC-884-1007',
    phone: '+855 15 777 602',
    bank: 'Sathapana',
    recentTransferCount: 6,
    lastTransferAt: '2026-04-19T08:42:00.000Z',
  },
  {
    id: 'u-8',
    name: 'Borey Chhim',
    initials: 'BC',
    accountId: 'AC-884-1008',
    phone: '+855 89 400 118',
    bank: 'Sathapana',
    recentTransferCount: 4,
    lastTransferAt: '2026-04-17T17:20:00.000Z',
  },
  {
    id: 'u-9',
    name: 'Sokly Heng',
    initials: 'SH',
    accountId: 'AC-884-1009',
    phone: '+855 97 220 908',
    bank: 'Sathapana',
    recentTransferCount: 3,
    lastTransferAt: '2026-04-16T12:34:00.000Z',
  },
  {
    id: 'u-10',
    name: 'Rina Pov',
    initials: 'RP',
    accountId: 'AC-884-1010',
    phone: '+855 86 909 144',
    bank: 'Sathapana',
    recentTransferCount: 2,
    lastTransferAt: '2026-04-13T15:02:00.000Z',
  },
];

export const splitItTransactions: SplitItTransaction[] = [
  {
    id: 'txn-1001',
    merchant: 'Brown Coffee BKK',
    amount: 24,
    currency: 'USD',
    postedAt: '2026-04-20T08:15:00.000Z',
    category: 'Cafe',
    participantsHint: ['u-1', 'u-2'],
    receiptAvailable: true,
  },
  {
    id: 'txn-1002',
    merchant: 'Lucky Supermarket',
    amount: 62.4,
    currency: 'USD',
    postedAt: '2026-04-18T18:45:00.000Z',
    category: 'Groceries',
    participantsHint: ['u-2', 'u-3', 'u-4'],
    receiptAvailable: true,
  },
  {
    id: 'txn-1003',
    merchant: 'Fuel Station 271',
    amount: 38,
    currency: 'USD',
    postedAt: '2026-04-15T12:05:00.000Z',
    category: 'Transport',
    participantsHint: ['u-3'],
    receiptAvailable: false,
  },
  {
    id: 'txn-1004',
    merchant: 'Malis Restaurant',
    amount: 96,
    currency: 'USD',
    postedAt: '2026-04-12T20:11:00.000Z',
    category: 'Dining',
    participantsHint: ['u-1', 'u-2', 'u-3', 'u-5'],
    receiptAvailable: true,
  },
  {
    id: 'txn-1005',
    merchant: 'Aeon Mall Food Court',
    amount: 44.5,
    currency: 'USD',
    postedAt: '2026-04-10T13:22:00.000Z',
    category: 'Dining',
    participantsHint: ['u-2', 'u-4'],
    receiptAvailable: true,
  },
  {
    id: 'txn-1006',
    merchant: '7-Eleven Riverside',
    amount: 12.75,
    currency: 'USD',
    postedAt: '2026-04-08T21:08:00.000Z',
    category: 'Convenience',
    participantsHint: ['u-1'],
    receiptAvailable: false,
  },
  {
    id: 'txn-1007',
    merchant: 'Cinema Legend',
    amount: 36,
    currency: 'USD',
    postedAt: '2026-04-07T19:40:00.000Z',
    category: 'Entertainment',
    participantsHint: ['u-3', 'u-5'],
    receiptAvailable: true,
  },
  {
    id: 'txn-1008',
    merchant: 'PassApp Ride',
    amount: 18.2,
    currency: 'USD',
    postedAt: '2026-04-05T22:10:00.000Z',
    category: 'Transport',
    participantsHint: ['u-4'],
    receiptAvailable: false,
  },
  {
    id: 'txn-1009',
    merchant: 'BBQ Plaza',
    amount: 71.3,
    currency: 'USD',
    postedAt: '2026-04-03T20:35:00.000Z',
    category: 'Dining',
    participantsHint: ['u-1', 'u-2', 'u-3'],
    receiptAvailable: true,
  },
  {
    id: 'txn-1010',
    merchant: 'Phsar Thom Grocery',
    amount: 53.9,
    currency: 'USD',
    postedAt: '2026-04-01T17:18:00.000Z',
    category: 'Groceries',
    participantsHint: ['u-2', 'u-5'],
    receiptAvailable: true,
  },
];

export const splitItDefaultDraft: SplitDraft = {
  amountInput: '',
  currency: 'USD',
  includeOwner: true,
  participantIds: [],
  splitMethod: 'equal',
  customAmounts: {},
  percentageShares: {},
  unitShares: {},
  receiptItems: [],
  note: '',
  reminderSettings: {
    enabled: true,
    frequency: 'daily',
  },
  instantSplitAfterPayment: true,
  phoneInvites: [],
};

export const splitItSentRequests: SplitRequest[] = [
  {
    id: 'sent-1001',
    createdAt: '2026-04-22T12:30:00.000Z',
    requestedBy: splitItCurrentUser.id,
    totalAmount: 96,
    currency: 'USD',
    splitMethod: 'equal',
    participantIds: ['u-1', 'u-2', 'u-3', 'u-5'],
    transactionId: 'txn-1004',
    receiptFileName: 'malis-dinner-receipt.jpg',
    note: 'Dinner split from last night. Please check your share.',
    reminderSettings: {
      enabled: true,
      frequency: 'daily',
    },
    instantSplitAfterPayment: true,
    phoneInvites: [],
    allocations: [
      { participantId: 'u-1', amount: 24 },
      { participantId: 'u-2', amount: 24 },
      { participantId: 'u-3', amount: 24 },
      { participantId: 'u-5', amount: 24 },
    ],
    notifications: [
      {
        id: 'notif-sent-1001-u1',
        participantId: 'u-1',
        participantName: 'Sophea Chan',
        accountId: 'AC-884-1001',
        amount: 24,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for Malis Restaurant.',
        status: 'viewed',
        paymentStatus: 'paid',
        paidAt: '2026-04-22T13:08:00.000Z',
        channel: 'push',
        sentAt: '2026-04-22T12:31:00.000Z',
      },
      {
        id: 'notif-sent-1001-u2',
        participantId: 'u-2',
        participantName: 'Dara Kim',
        accountId: 'AC-884-1002',
        amount: 24,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for Malis Restaurant.',
        status: 'delivered',
        paymentStatus: 'pending',
        channel: 'in_app',
        sentAt: '2026-04-22T12:31:00.000Z',
      },
      {
        id: 'notif-sent-1001-u3',
        participantId: 'u-3',
        participantName: 'Sothea Ung',
        accountId: 'AC-884-1003',
        amount: 24,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for Malis Restaurant.',
        status: 'delivered',
        paymentStatus: 'pending',
        channel: 'push',
        sentAt: '2026-04-22T12:31:00.000Z',
      },
      {
        id: 'notif-sent-1001-u5',
        participantId: 'u-5',
        participantName: 'Mony Vichea',
        accountId: 'AC-884-1005',
        amount: 24,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for Malis Restaurant.',
        status: 'queued',
        paymentStatus: 'pending',
        channel: 'in_app',
        sentAt: '2026-04-22T12:31:00.000Z',
      },
    ],
  },
  {
    id: 'sent-1002',
    createdAt: '2026-04-19T16:45:00.000Z',
    requestedBy: splitItCurrentUser.id,
    totalAmount: 44.5,
    currency: 'USD',
    splitMethod: 'amount',
    participantIds: ['u-2', 'u-4'],
    transactionId: 'txn-1005',
    receiptFileName: 'aeon-food-court.jpg',
    reminderSettings: {
      enabled: true,
      frequency: 'weekly',
    },
    instantSplitAfterPayment: false,
    phoneInvites: [],
    allocations: [
      { participantId: 'u-2', amount: 20 },
      { participantId: 'u-4', amount: 24.5 },
    ],
    notifications: [
      {
        id: 'notif-sent-1002-u2',
        participantId: 'u-2',
        participantName: 'Dara Kim',
        accountId: 'AC-884-1002',
        amount: 20,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for Aeon Mall Food Court.',
        status: 'viewed',
        paymentStatus: 'paid',
        paidAt: '2026-04-19T17:01:00.000Z',
        channel: 'push',
        sentAt: '2026-04-19T16:46:00.000Z',
      },
      {
        id: 'notif-sent-1002-u4',
        participantId: 'u-4',
        participantName: 'Nika Touch',
        accountId: 'AC-884-1004',
        amount: 24.5,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for Aeon Mall Food Court.',
        status: 'viewed',
        paymentStatus: 'paid',
        paidAt: '2026-04-19T17:18:00.000Z',
        channel: 'in_app',
        sentAt: '2026-04-19T16:46:00.000Z',
      },
    ],
  },
  {
    id: 'sent-1003',
    createdAt: '2026-04-17T09:15:00.000Z',
    requestedBy: splitItCurrentUser.id,
    totalAmount: 18.2,
    currency: 'USD',
    splitMethod: 'equal',
    participantIds: ['u-4'],
    transactionId: 'txn-1008',
    reminderSettings: {
      enabled: true,
      frequency: 'daily',
    },
    instantSplitAfterPayment: true,
    phoneInvites: [
      {
        id: 'invite-1003-1',
        phone: '+855 12 888 431',
        message: 'Rasmey Sophorn invited you to SplitIt on Sathapana Mobile.',
        status: 'sms_sent',
      },
    ],
    allocations: [
      { participantId: 'u-4', amount: 18.2 },
    ],
    notifications: [
      {
        id: 'notif-sent-1003-u4',
        participantId: 'u-4',
        participantName: 'Nika Touch',
        accountId: 'AC-884-1004',
        amount: 18.2,
        currency: 'USD',
        message: 'Rasmey Sophorn requested your share for PassApp Ride.',
        status: 'queued',
        paymentStatus: 'pending',
        channel: 'push',
        sentAt: '2026-04-17T09:16:00.000Z',
      },
    ],
  },
];

export const splitItIncomingRequests: SplitIncomingRequest[] = [
  {
    id: 'incoming-1001',
    createdAt: '2026-04-21T09:20:00.000Z',
    ownerName: 'Sophea Chan',
    ownerAccountId: 'AC-884-1001',
    totalAmount: 24,
    yourAmount: 8,
    currency: 'USD',
    splitMethod: 'equal',
    participantCount: 3,
    transactionId: 'txn-1001',
    receiptFileName: 'brown-coffee-receipt.jpg',
    status: 'payment_due',
    message: 'Your share is ready for payment.',
    participants: [
      {
        id: 'me',
        name: 'You',
        accountId: splitItCurrentUser.accountId,
        amount: 8,
        status: 'pending',
        isYou: true,
      },
      {
        id: 'u-1',
        name: 'Sophea Chan',
        accountId: 'AC-884-1001',
        amount: 8,
        status: 'paid',
      },
      {
        id: 'u-2',
        name: 'Dara Kim',
        accountId: 'AC-884-1002',
        amount: 8,
        status: 'pending',
      },
    ],
  },
  {
    id: 'incoming-1002',
    createdAt: '2026-04-20T18:10:00.000Z',
    ownerName: 'Piseth Lim',
    ownerAccountId: 'AC-884-1006',
    totalAmount: 62.4,
    yourAmount: 15.6,
    currency: 'USD',
    splitMethod: 'amount',
    participantCount: 4,
    transactionId: 'txn-1002',
    note: 'Please review your grocery share.',
    status: 'pending_review',
    message: 'Review the assigned amount before payment.',
    participants: [
      {
        id: 'me',
        name: 'You',
        accountId: splitItCurrentUser.accountId,
        amount: 15.6,
        status: 'pending',
        isYou: true,
      },
      {
        id: 'u-6',
        name: 'Piseth Lim',
        accountId: 'AC-884-1006',
        amount: 15.6,
        status: 'paid',
      },
      {
        id: 'u-3',
        name: 'Sothea Ung',
        accountId: 'AC-884-1003',
        amount: 15.6,
        status: 'pending',
      },
      {
        id: 'u-4',
        name: 'Nika Touch',
        accountId: 'AC-884-1004',
        amount: 15.6,
        status: 'pending',
      },
    ],
  },
];
